/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/signin": {
    /** Sign in a user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SigninRequest"];
        };
      };
      responses: {
        /** @description Successful login */
        200: {
          content: {
            "application/json": components["schemas"]["SigninRequest"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/signup": {
    /** Register a new user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignupRequest"];
        };
      };
      responses: {
        /** @description User created */
        201: {
          content: {
            "application/json": components["schemas"]["SignupResponse"];
          };
        };
        /** @description Invalid input */
        400: {
          content: never;
        };
      };
    };
  };
  "/auth/change-password": {
    /** Change user password */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"];
        };
      };
      responses: {
        /** @description Password change successful */
        200: {
          content: {
            "application/json": components["schemas"]["ChangePasswordResponse"];
          };
        };
        /** @description Invalid input or password */
        400: {
          content: never;
        };
      };
    };
  };
  "/api/healthcheck": {
    /**
     * Health Check
     * @description Responds if the app is up and running
     */
    get: {
      responses: {
        /** @description App is up and running */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/users": {
    /** Get a list of users */
    get: {
      responses: {
        /** @description A list of users */
        200: {
          content: {
            "application/json": components["schemas"]["UserResponse"][];
          };
        };
      };
    };
  };
  "/api/products": {
    /** Get a list of products */
    get: {
      responses: {
        /** @description A list of products */
        200: {
          content: {
            "application/json": components["schemas"]["ProductResponse"][];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SigninRequest: {
      /** @example johndoe */
      username: string;
      /** @example password123 */
      password: string;
    };
    SigninResponse: {
      /** @example User signed in successfully */
      message?: string;
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      token?: string;
      /** @example johndoe */
      username?: string;
      /** @example John */
      firstName?: string;
      /** @example Doe */
      lastName?: string;
      /** @example user */
      role?: string;
    };
    SignupRequest: {
      /** @example John */
      firstName: string;
      /** @example Doe */
      lastName: string;
      /** @example johndoe */
      username: string;
      /** @example password123 */
      password: string;
    };
    SignupResponse: {
      /** @example User created successfully */
      message?: string;
      /** @example 12345 */
      userId?: string;
    };
    ChangePasswordRequest: {
      /** @example johndoe */
      username: string;
      /** @example oldpassword123 */
      oldPassword: string;
      /** @example newpassword123 */
      newPassword: string;
    };
    ChangePasswordResponse: {
      /** @example Password changed successfully */
      message?: string;
    };
    UserResponse: {
      /** @example johndoe */
      username?: string;
      /** @example John */
      firstName?: string;
      /** @example Doe */
      lastName?: string;
      /** @example user */
      role?: string;
    };
    ProductResponse: {
      /** @example 1 */
      id?: string;
      /** @example Product 1 */
      name?: string;
      /** @example 19.99 */
      price?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
