// This file is auto-generated by @hey-api/openapi-ts

export const $SigninRequest = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'johndoe'
        },
        password: {
            type: 'string',
            example: 'password123'
        }
    },
    required: ['username', 'password']
} as const;

export const $SigninResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'User signed in successfully'
        },
        token: {
            type: 'string',
            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        },
        username: {
            type: 'string',
            example: 'johndoe'
        },
        firstName: {
            type: 'string',
            example: 'John'
        },
        lastName: {
            type: 'string',
            example: 'Doe'
        },
        role: {
            type: 'string',
            example: 'user'
        }
    }
} as const;

export const $SignupRequest = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            example: 'John'
        },
        lastName: {
            type: 'string',
            example: 'Doe'
        },
        username: {
            type: 'string',
            example: 'johndoe'
        },
        password: {
            type: 'string',
            example: 'password123'
        }
    },
    required: ['firstName', 'lastName', 'username', 'password']
} as const;

export const $SignupResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'User created successfully'
        },
        userId: {
            type: 'string',
            example: '12345'
        }
    }
} as const;

export const $ChangePasswordRequest = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'johndoe'
        },
        oldPassword: {
            type: 'string',
            example: 'oldpassword123'
        },
        newPassword: {
            type: 'string',
            example: 'newpassword123'
        }
    },
    required: ['username', 'oldPassword', 'newPassword']
} as const;

export const $ChangePasswordResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'Password changed successfully'
        }
    }
} as const;

export const $UserResponse = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'johndoe'
        },
        firstName: {
            type: 'string',
            example: 'John'
        },
        lastName: {
            type: 'string',
            example: 'Doe'
        },
        role: {
            type: 'string',
            example: 'user'
        }
    }
} as const;

export const $ProductResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '1'
        },
        name: {
            type: 'string',
            example: 'Product 1'
        },
        price: {
            type: 'number',
            example: 19.99
        }
    }
} as const;